name: TURKHUB KEY SYSTEM

on:
  schedule:
    - cron: '20 8 * * *'   # 15:20 เวลาไทย
  workflow_dispatch:

jobs:
  generate-key:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:

    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Generate Key
      run: |
        KEY="TURKHUB-$(openssl rand -hex 3)"
        echo $KEY > KEY
        echo "KEY=$KEY" >> $GITHUB_ENV

    - name: Commit Key
      run: |
        git config user.name "turkhub-bot"
        git config user.email "bot@github.com"
        git add KEY
        git commit -m "🔑 Key Update" || echo "No changes to commit"
        git push

    - name: Send Key To Discord
      run: |
        curl -H "Content-Type: application/json" \
        -d '{
        "content": "@everyone",
        "embeds":[
          {
            "title":"🗝️ TURK HUB KEY",
            "description":"New key generated at 15:20 (Thailand Time)",
            "color":5763719,
            "fields":[
              {
                "name":"Copy Key",
                "value":"`'${{ env.KEY }}'`"
              }
            ],
            "footer":{
              "text":"TURK HUB KEY SYSTEM"
            }
          }
        ]
        }' \
        https://discord.com/api/webhooks/1479462633383006373/p_GjlNQrYuQuZulcen9SxJExpZMF4oYdqQsMD235rYvmapsBTIQdhoHXlmrz0gzEkVLO